// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtaDg99SjKYftjxMw12whlfcna46vHSIM',
    appId: '1:914558835753:web:f3ce440a0444f7f7c3d038',
    messagingSenderId: '914558835753',
    projectId: 'eventpulse-5521a',
    authDomain: 'eventpulse-5521a.firebaseapp.com',
    storageBucket: 'eventpulse-5521a.firebasestorage.app',
    measurementId: 'G-M72CBWMQF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGEuE7lSWuE_0397dqvy-8KlLCG1VdjkA',
    appId: '1:914558835753:android:570e150d5bba45bfc3d038',
    messagingSenderId: '914558835753',
    projectId: 'eventpulse-5521a',
    storageBucket: 'eventpulse-5521a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtKpfznVwsvZtAs93hCzvdmoemj7PW0U',
    appId: '1:914558835753:ios:4cfe76bfd629d982c3d038',
    messagingSenderId: '914558835753',
    projectId: 'eventpulse-5521a',
    storageBucket: 'eventpulse-5521a.firebasestorage.app',
    androidClientId: '914558835753-tbol2r2rlkq7vb1vj26h4o90t70dd4mj.apps.googleusercontent.com',
    iosClientId: '914558835753-q6td2ruhbrn5ellb9cpoc53f987i73dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.evenpulseApplication',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVtKpfznVwsvZtAs93hCzvdmoemj7PW0U',
    appId: '1:914558835753:ios:4cfe76bfd629d982c3d038',
    messagingSenderId: '914558835753',
    projectId: 'eventpulse-5521a',
    storageBucket: 'eventpulse-5521a.firebasestorage.app',
    androidClientId: '914558835753-tbol2r2rlkq7vb1vj26h4o90t70dd4mj.apps.googleusercontent.com',
    iosClientId: '914558835753-q6td2ruhbrn5ellb9cpoc53f987i73dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.evenpulseApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtaDg99SjKYftjxMw12whlfcna46vHSIM',
    appId: '1:914558835753:web:954f06443c31ce04c3d038',
    messagingSenderId: '914558835753',
    projectId: 'eventpulse-5521a',
    authDomain: 'eventpulse-5521a.firebaseapp.com',
    storageBucket: 'eventpulse-5521a.firebasestorage.app',
    measurementId: 'G-X0Y3PCLDXE',
  );
}
